# Generated by Django 4.1.3 on 2023-10-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='features',
            new_name='featured',
        ),
    ]
